config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shows do
    resources :reviews do
      resources :comments
    end
  end
  root "welcome#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, presence: true, length: { in: (20..320) }
  validates :review, presence: true, uniqueness: :true
  validates :user, presence: true, uniqueness: :true
  belongs_to :review
  belongs_to :user
  def owner?(current_user)
    user == current_user
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :shows

  validates :name,
    presence: true, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :votes
  has_many :comments

  belongs_to :user
  belongs_to :show

  validates :user,
    presence: true
  validates :show,
    presence: true
  validates :title,
    presence: true
  validates :body,
    presence: true
  validates :score,
  presence: true
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :reviews
  belongs_to :genre

  validates :name,
    presence: true, uniqueness: true
  validates :description,
    presence: true
  validates :genre,
    presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: { in: (6..32) }

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @show = Show.find(params[:show_id])
    @review = Review.find(params[:review_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.review_id = params[:review_id]
    if @comment.save
      flash[:notice] = "Comment created successfully"
      redirect_to show_path(params[:show_id])
    else
      @show = Show.find(params[:show_id])
      @review = Review.find(params[:review_id])
      flash[:notice] = "You didn't enter enough information."
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @review = Review.find(params[:review_id])
    @show = Show.find(params[:show_id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment updated successfully"
      redirect_to show_path(params[:show_id])
    else
      flash[:notice] = "You didn't enter enough information."
      render :edit
    end
  end

  def show
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:notice] = "Comment deleted successfully"
      redirect_to show_path(params[:show_id])
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
    @show = Show.find(@review.show_id)
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice]= "Review updated successfully"
      redirect_to show_path(params[:show_id])
    else
      flash[:notice]= "You didn't enter enough information."
      render 'edit'
    end
  end

  def create
    @review = Review.new(review_params)
    @review.show_id = params[:show_id]
    @review.user_id = current_user.id
    if @review.save
      flash[:notice]= "Review created successfully"
      redirect_to show_path(params[:show_id])
    else
      flash[:notice]= "You didn't enter enough information."
      render :new
    end
  end

  def show
    @review_id = params[:id]
    @review = Review.destroy(@review_id)
    if @review.save
      flash[:notice] = "Review deleted successfully"
      redirect_to show_path(params[:show_id])
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :body)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @shows = Show.all
  end

  def show
    @show = Show.find(params[:id])
    @review = Review.new
    @comment = Comment.new
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<h2>Edit a comment</h2>

<%= form_for [@show, @review, @comment] do |f| %>

  <div><%= f.label :text %><br />
  <%= f.text_area :text %></div>

  <div><%= f.submit "Submit Comment" %></div>
<% end %>

app/views/comments/new.html.erb
<h2>Write a comment</h2>
<%= form_for [@show, @review, @comment] do |f| %>

  <div><%= f.label :text %><br />
  <%= f.text_area :text %></div>

  <div><%= f.submit "Submit Comment" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blueshift</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to "Sign up", new_user_registration_path %>
<%= yield %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</body>
</html>

app/views/reviews/edit.html.erb
<h2> Update review </h2>

<%= form_for [@show, @review] do |f| %>

  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :body %><br />
  <%= f.text_area :body %></div>

  <div><%= f.submit "Edit review" %></div>
<% end %>

app/views/reviews/new.html.erb
<h2>Write a review</h2>

<%= form_for [@show, @review] do |f| %>

  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :body %><br />
  <%= f.text_area :body %></div>

  <div><%= f.submit "Add review" %></div>
<% end %>

app/views/shows/index.html.erb
List of shows:

<% @shows.each do |show| %>
  <%= link_to show.name, show_path(show) %>
<% end %>

app/views/shows/show.html.erb
<h2>Add Review Here</h2>

<%= form_for [@show, @review] do |f| %>

  <div><%= f.label :title %><br />
  <%= f.text_field :title %></div>

  <div><%= f.label :body %><br />
  <%= f.text_area :body %></div>

  <div><%= f.submit "Add review" %></div>
<% end %>

<ul>
<% @show.reviews.each do |review| %>
  <li>
    <p>
      <%= review.title %>
    </p>
    <p>
      <%= review.body %>
    </p>
    <ul>
      <% review.comments.each do |comment| %>
        <li>
          <%= comment.text %>

          <% if comment.owner?(current_user) %>
            <%= link_to "Edit comment", edit_show_review_comment_path(@show, review, comment)   %>
            <%= link_to "Delete comment", show_review_comment_path(@show, review, comment)   %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= link_to "Edit review", edit_show_review_path(@show, review) %>
    <%= link_to "Delete review", show_review_path(@show, review) %>
    <%= link_to "Add comment", new_show_review_comment_path(@show, review, @comment)   %>
  </li>

<% end %>

</ul>